### ISSUE TITLE
Ledger doesn't display correctly when signing new delegate transaction 

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/ledger#1]
It all works and the transaction is signed, but the screen on the ledger doesn't show in the same way as other transaction types. I'll take a picture when I get chance and add it to this issue.

**Comment by alexbarnsley** [comment]
![img_20170929_203923](https://user-images.githubusercontent.com/8069294/31033022-80ee6636-a556-11e7-8c96-65d25324390d.jpg)

No message on confirmation screen

**Comment by fix** [comment]
yes it is impossible to run a delegate with a ledger key so far

**Comment by fix** [comment]
but that could be in the future, have to find a way to do it

**Comment by alexbarnsley** [comment]
It's an interesting problem to have! I forgot I created this issue. The current way of forging is by providing a passphrase isn't it?

**Comment by fix** [comment]
@alexbarnsley any news about this issue, i have not followed up it
